name: First Workflow
on: workflow_dispatch # it's manually starting workflow
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print Goodbye
        run: echo "Done - bye!"
        
